You have to work on the files:
*  [Books](https://github.com/gdv/foundationsCS/raw/master/progetti/2021/Books.csv.gz)
*  [Book ratings](https://github.com/gdv/foundationsCS/raw/master/progetti/2021/Book-Ratings.csv.gz)
*  [Users](https://github.com/gdv/foundationsCS/raw/master/progetti/2021/Users.csv.gz)
*  [Goodbooks books](https://github.com/gdv/foundationsCS/raw/master/progetti/2021/goodbooks.csv.gz)
*  [Goodbooks ratings](https://github.com/gdv/foundationsCS/raw/master/progetti/2021/goodbooks-ratings.csv.gz)

### Notes

1.    It is mandatory to use GitHub for developing the project.
1.    The project must be a jupyter notebook.
1.    There is no restriction on the libraries that can be used, nor on the Python version.
1.    To read those files, you need to use the `encoding = 'latin-1'` option.
1.    All questions on the project **must** be asked in a public channel on [Zulip](https://focs.zulipchat.com), otherwise no  answer will be given.

In [244]:
import ast
from datetime import datetime, timedelta
import pandas as pd

In [245]:
## Apri i diversi file
path = '/home/alex/Desktop/FOUNDATIONS/'
books = path+'Books.csv'

In [246]:
df_books = pd.read_csv(books, sep=";", encoding ='latin1',dtype='unicode')

In [247]:
df_books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271354,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271355,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271356,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271357,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271358,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

In [248]:
book_rating = path+'Book-Ratings.csv'

In [249]:
df_ratings = pd.read_csv(book_rating, sep=";", encoding ='latin1',dtype='unicode')

In [250]:
df_ratings.head()

  User-ID        ISBN Book-Rating
0  276725  034545104X           0
1  276726  0155061224           5
2  276727  0446520802           0
3  276729  052165615X           3
4  276729  0521795028           6

In [251]:
users= path+'Users.csv'
df_users = pd.read_csv(users, sep=";", encoding ='latin1',dtype='unicode')
df_users.head()

  User-ID                            Location  Age
0       1                  nyc, new york, usa  NaN
1       2           stockton, california, usa   18
2       3     moscow, yukon territory, russia  NaN
3       4           porto, v.n.gaia, portugal   17
4       5  farnborough, hants, united kingdom  NaN

In [252]:
goodbooks= path+'goodbooks.csv'
df_goodbooks = pd.read_csv(goodbooks, sep=",", encoding ='latin1',dtype='unicode')
df_goodbooks.head()

,book_id,goodreads_book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,title,language_code,average_rating,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url
0,1,2767052,2767052,2792775,272,439023483,9.78043902348e+12,Suzanne Collins,2008.0,The Hunger Games,"The Hunger Games (The Hunger Games, #1)",eng,4.34,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...
1,2,3,3,4640799,491,439554934,9.78043955493e+12,"J.K. Rowling, Mary GrandPrÃ©",1997.0,Harry Potter and the Philosopher's Stone,Harry Potter and the Sorcerer's Stone (Harry P...,eng,4.44,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...
2,3,41865,41865,3212258,226,316015849,9.78031601584e+12,Stephenie Meyer,2005.0,Twilight,"Twilight (Twilight, #1)",en-US,3.57,3866839,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...
3,4,2657,2657,3275794,487,61120081,9.78006112008e+12,Harper Lee,1960.0,To Kill a Mockingbird,To Kill a Mockingbird,eng,4.25,3198671,3340896,72586,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...
4,5,4671,4671,245494,1356,743273567,9.78074327356e+12,F. Scott Fitzgerald,1925.0,The Great Gatsby,The Great Gatsby,eng,3.89,2683664,2773745,51992,86236,197621,606158,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...

In [253]:
gb_rating= path+'goodbooks-ratings.csv'
df_gb_rating = pd.read_csv(gb_rating, sep=",", encoding ='latin1',dtype='unicode')
df_gb_rating.head()

  user_id book_id rating
0       1     258      5
1       2    4081      4
2       2     260      5
3       2    9296      5
4       2    2318      3

### 1. Normalize the location field of *Users* dataset, splitting into city, region, country.

In [254]:
## Costruisco un nuovo dataset contente i campi di "location"
df = df_users['Location'].str.split(',', expand=True)

In [255]:
df.columns = ['City', 'Region', 'Country', 'Droppa1' , 'Droppa2' , 'Droppa3' , 'Droppa4' , 'Droppa5' , 'Droppa6']
to_keep = df[['City' , 'Region' , 'Country']]

In [256]:
## Merge tra il dataset delle location e users iniziale
df_users_fin =  pd.concat([df_users, to_keep], axis=1)
df_users_fin.drop('Location', inplace=True, axis=1)
df_users_fin.head()

  User-ID  Age         City            Region          Country
0       1  NaN          nyc          new york              usa
1       2   18     stockton        california              usa
2       3  NaN       moscow   yukon territory           russia
3       4   17        porto          v.n.gaia         portugal
4       5  NaN  farnborough             hants   united kingdom

### 2. For each book in the *Books* dataset, compute its average rating.

In [257]:
## Provo a uniformare gli ISBN, poichè molte entry sono errate
df_ratings["ISBN"] =df_ratings["ISBN"].apply(lambda x: x.strip().strip("\'").strip("\\").strip('\"').strip("\#").strip("(").strip(")").strip('*').strip('+').strip('/').strip(',.').strip('.').strip('/'))

In [258]:
df_ratings['Book-Rating'] = df_ratings['Book-Rating'].astype('float64')

In [259]:
book_groupby = df_ratings.groupby("ISBN")

In [260]:
### Calcolo la media sul raggruppamento per ISBN dei libri
average_book_rating = book_groupby["Book-Rating"].mean()

In [261]:
average_book_rating = average_book_rating.to_frame()

In [262]:
average_book_rating

               Book-Rating
ISBN
0 00 612183 7          0.0
0 00 614494 2          0.0
0 00 655241 2          8.0
0 09 944678 2          9.0
0 14 02.9640           9.0
...                    ...
cn113107               0.0
ooo7156103             7.0
Â§423350229            0.0
Â´3499128624           8.0
ÃÂ½crosoft            7.0

[340534 rows x 1 columns]

In [263]:
### Left join tra books e le medie calcolate
df_books = df_books.join(average_book_rating, on="ISBN")

In [264]:
df_books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,Book-Rating
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,0.000000
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,4.928571
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,5.000000
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,4.272727
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,0.000000
...,...,...,...,...,...,...,...,...,...
271354,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,7.000000
271355,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,4.000000
271356,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,0.000000
271357,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,0.000000
271358,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,0.000000

### 3. For each book in the *GoodBooks* dataset, compute its average rating.

In [265]:
pd.set_option('display.max_columns', None)
df_goodbooks

,book_id,goodreads_book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,title,language_code,average_rating,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url
0,1,2767052,2767052,2792775,272,439023483,9.78043902348e+12,Suzanne Collins,2008.0,The Hunger Games,"The Hunger Games (The Hunger Games, #1)",eng,4.34,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...
1,2,3,3,4640799,491,439554934,9.78043955493e+12,"J.K. Rowling, Mary GrandPrÃ©",1997.0,Harry Potter and the Philosopher's Stone,Harry Potter and the Sorcerer's Stone (Harry P...,eng,4.44,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...
2,3,41865,41865,3212258,226,316015849,9.78031601584e+12,Stephenie Meyer,2005.0,Twilight,"Twilight (Twilight, #1)",en-US,3.57,3866839,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...
3,4,2657,2657,3275794,487,61120081,9.78006112008e+12,Harper Lee,1960.0,To Kill a Mockingbird,To Kill a Mockingbird,eng,4.25,3198671,3340896,72586,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...
4,5,4671,4671,245494,1356,743273567,9.78074327356e+12,F. Scott Fitzgerald,1925.0,The Great Gatsby,The Great Gatsby,eng,3.89,2683664,2773745,51992,86236,197621,606158,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,95,5297,5297,1858012,2303,375751513,9.78037575152e+12,"Oscar Wilde, Jeffrey Eugenides",1891.0,The Picture of Dorian Gray,The Picture of Dorian Gray,eng,4.06,590014,674551,19647,9825,30735,129420,246892,257679,https://images.gr-assets.com/books/1424596966m...,https://images.gr-assets.com/books/1424596966s...
95,96,13536860,13536860,18034963,133,345803507,9.7803458035e+12,E.L. James,2012.0,Fifty Shades Freed,"Fifty Shades Freed (Fifty Shades, #3)",eng,3.88,387290,610116,25287,39079,55691,109963,140304,265079,https://images.gr-assets.com/books/1336418837m...,https://images.gr-assets.com/books/1336418837s...
96,97,17245,17245,3165724,2207,393970124,9.78039397013e+12,"Bram Stoker, Nina Auerbach, David J. Skal",1897.0,Dracula,Dracula,eng,3.98,618973,689739,17263,11756,36719,151396,246043,243825,https://images.gr-assets.com/books/1387151694m...,https://images.gr-assets.com/books/1387151694s...
97,98,5060378,5060378,6976108,209,307269981,9.78030726998e+12,"Stieg Larsson, Reg Keeland",2006.0,Flickan som lekte med elden,"The Girl Who Played with Fire (Millennium, #2)",eng,4.22,563994,649253,31423,4623,15781,91021,258236,279592,https://images.gr-assets.com/books/1351778881m...,https://images.gr-assets.com/books/1351778881s...
98,99,11857408,11857408,16813814,147,1612130585,9.78161213058e+12,E.L. James,2011.0,Fifty Shades Darker,"Fifty Shades Darker (Fifty Shades, #2)",eng,3.87,552059,623340,28052,37245,58935,114203,150906,262051,https://images.gr-assets.com/books/1358266080m...,https://images.gr-assets.com/books/1358266080s...

In [266]:
### Imposto il tipo corretto per poter eseguire la somma
df_goodbooks['ratings_1'] = df_goodbooks['ratings_1'].astype(int)
df_goodbooks['ratings_2'] = df_goodbooks['ratings_2'].astype(int)
df_goodbooks['ratings_3'] = df_goodbooks['ratings_3'].astype(int)
df_goodbooks['ratings_4'] = df_goodbooks['ratings_4'].astype(int)
df_goodbooks['ratings_5'] = df_goodbooks['ratings_5'].astype(int)
df_goodbooks['work_ratings_count'] = df_goodbooks['work_ratings_count'].astype(int)

In [267]:
### Calcolo il rating con i pesi corretti per ogni valutazione
df_goodbooks['avg_rating'] = (df_goodbooks['ratings_1'] + df_goodbooks['ratings_2'] *2 + df_goodbooks['ratings_3']*3 + df_goodbooks['ratings_4']*4+ df_goodbooks['ratings_5']*5 )/df_goodbooks['work_ratings_count']

In [268]:
df_goodbooks

,book_id,goodreads_book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,title,language_code,average_rating,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url,avg_rating
0,1,2767052,2767052,2792775,272,439023483,9.78043902348e+12,Suzanne Collins,2008.0,The Hunger Games,"The Hunger Games (The Hunger Games, #1)",eng,4.34,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,4.341984
1,2,3,3,4640799,491,439554934,9.78043955493e+12,"J.K. Rowling, Mary GrandPrÃ©",1997.0,Harry Potter and the Philosopher's Stone,Harry Potter and the Sorcerer's Stone (Harry P...,eng,4.44,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...,4.443047
2,3,41865,41865,3212258,226,316015849,9.78031601584e+12,Stephenie Meyer,2005.0,Twilight,"Twilight (Twilight, #1)",en-US,3.57,3866839,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...,3.571067
3,4,2657,2657,3275794,487,61120081,9.78006112008e+12,Harper Lee,1960.0,To Kill a Mockingbird,To Kill a Mockingbird,eng,4.25,3198671,3340896,72586,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...,4.254818
4,5,4671,4671,245494,1356,743273567,9.78074327356e+12,F. Scott Fitzgerald,1925.0,The Great Gatsby,The Great Gatsby,eng,3.89,2683664,2773745,51992,86236,197621,606158,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...,3.887376
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,95,5297,5297,1858012,2303,375751513,9.78037575152e+12,"Oscar Wilde, Jeffrey Eugenides",1891.0,The Picture of Dorian Gray,The Picture of Dorian Gray,eng,4.06,590014,674551,19647,9825,30735,129420,246892,257679,https://images.gr-assets.com/books/1424596966m...,https://images.gr-assets.com/books/1424596966s...,4.055317
95,96,13536860,13536860,18034963,133,345803507,9.7803458035e+12,E.L. James,2012.0,Fifty Shades Freed,"Fifty Shades Freed (Fifty Shades, #3)",eng,3.88,387290,610116,25287,39079,55691,109963,140304,265079,https://images.gr-assets.com/books/1336418837m...,https://images.gr-assets.com/books/1336418837s...,3.879526
96,97,17245,17245,3165724,2207,393970124,9.78039397013e+12,"Bram Stoker, Nina Auerbach, David J. Skal",1897.0,Dracula,Dracula,eng,3.98,618973,689739,17263,11756,36719,151396,246043,243825,https://images.gr-assets.com/books/1387151694m...,https://images.gr-assets.com/books/1387151694s...,3.976401
97,98,5060378,5060378,6976108,209,307269981,9.78030726998e+12,"Stieg Larsson, Reg Keeland",2006.0,Flickan som lekte med elden,"The Girl Who Played with Fire (Millennium, #2)",eng,4.22,563994,649253,31423,4623,15781,91021,258236,279592,https://images.gr-assets.com/books/1351778881m...,https://images.gr-assets.com/books/1351778881s...,4.220469
98,99,11857408,11857408,16813814,147,1612130585,9.78161213058e+12,E.L. James,2011.0,Fifty Shades Darker,"Fifty Shades Darker (Fifty Shades, #2)",eng,3.87,552059,623340,28052,37245,58935,114203,150906,262051,https://images.gr-assets.com/books/1358266080m...,https://images.gr-assets.com/books/1358266080s...,3.868840

### 4. Merge together all rows sharing the same book title, author and publisher. We will call the resulting datset `merged books`. The books that have not been merged together will not appear in `merged books`.

In [269]:
### Effettuo group by e conto il numero di apparizioni dei titoli per poter escludere quelli presenti solo 1 volta
raggruppamento = df_books.groupby(['Book-Title' , 'Book-Author' , 'Publisher']).count()

In [270]:
raggruppamento.head()

,,,ISBN,Year-Of-Publication,Image-URL-S,Image-URL-M,Image-URL-L,Book-Rating
Book-Title,Book-Author,Publisher,,,,,,
"A Light in the Storm: The Civil War Diary of Amelia Martin, Fenwick Island, Delaware, 1861 (Dear America)",Karen Hesse,Hyperion Books for Children,1,1,1,1,1,1
Always Have Popsicles,Rebecca Harvin,Rebecca L. Harvin,1,1,1,1,1,1
Apple Magic (The Collector's series),Martina Boudreau,Amer Cooking Guild,1,1,1,1,1,1
"Ask Lily (Young Women of Faith: Lily Series, Book 5)",Nancy N. Rue,Zonderkidz,1,1,1,1,1,1
Beyond IBM: Leadership Marketing and Finance for the 1990s,Lou Mobley,"Teleonet, Incorporated",1,1,1,1,1,1
...,...,...,...,...,...,...,...,...
Ã?Ã?lpiraten.,Janwillem van de Wetering,Rowohlt Tb.,1,1,1,1,1,1
Ã?Ã?rger mit Produkt X. Roman.,Joan Aiken,Diogenes Verlag,1,1,1,1,1,1
Ã?Ã?sterlich leben.,Anselm GrÃ?ÃÂ¼n,"Herder, Freiburg",1,1,1,1,1,1
Ã?Ã?stlich der Berge.,David Guterson,btb,1,1,1,1,1,1
Ã?Ã?thique en toc,Didier Daeninckx,Baleine,1,1,1,1,1,1

In [271]:
merged_books = raggruppamento[raggruppamento['ISBN'] >1]

In [272]:
merged_books.head()

                                                                                                           ISBN  \
Book-Title                                         Book-Author             Publisher
!%@ (A Nutshell handbook)                          Donnalyn Frey           O'Reilly                           2
'A Hell of a Place to Lose a Cow': An American ... Tim Brookes             National Geographic                2
10,000 dreams interpreted: A dictionary of dreams  Gustavus Hindman Miller Barnes &amp; Nobles Books          2
101 Famous Poems                                   Roy J. Cook             McGraw-Hill/Contemporary Books     3
15 Houseplants Even You Can't Kill                 Joe Elder               Berkley Pub Group                  2
...                                                                                                         ...
Zia                                                Scott O'Dell            Laurel-Leaf Books                  2
                                                                           Yearling Books                     2
Zimmermann Telegram                                Barbara Tuchman         Ballantine Books                   2
Zoids Chaotic Century (Zoids: Chaotic Century (... Michiro Ueyama          Viz Comics                         4
Ã?Ã?berleben in der WÃ?ÃÂ¼ste Danakil.         RÃ?ÃÂ¼diger Nehberg   Piper                              2

                                                                                                           Year-Of-Publication  \
Book-Title                                         Book-Author             Publisher
!%@ (A Nutshell handbook)                          Donnalyn Frey           O'Reilly                                          2
'A Hell of a Place to Lose a Cow': An American ... Tim Brookes             National Geographic                               2
10,000 dreams interpreted: A dictionary of dreams  Gustavus Hindman Miller Barnes &amp; Nobles Books                         2
101 Famous Poems                                   Roy J. Cook             McGraw-Hill/Contemporary Books                    3
15 Houseplants Even You Can't Kill                 Joe Elder               Berkley Pub Group                                 2
...                                                                                                                        ...
Zia                                                Scott O'Dell            Laurel-Leaf Books                                 2
                                                                           Yearling Books                                    2
Zimmermann Telegram                                Barbara Tuchman         Ballantine Books                                  2
Zoids Chaotic Century (Zoids: Chaotic Century (... Michiro Ueyama          Viz Comics                                        4
Ã?Ã?berleben in der WÃ?ÃÂ¼ste Danakil.         RÃ?ÃÂ¼diger Nehberg   Piper                                             2

                                                                                                           Image-URL-S  \
Book-Title                                         Book-Author             Publisher
!%@ (A Nutshell handbook)                          Donnalyn Frey           O'Reilly                                  2
'A Hell of a Place to Lose a Cow': An American ... Tim Brookes             National Geographic                       2
10,000 dreams interpreted: A dictionary of dreams  Gustavus Hindman Miller Barnes &amp; Nobles Books                 2
101 Famous Poems                                   Roy J. Cook             McGraw-Hill/Contemporary Books            3
15 Houseplants Even You Can't Kill                 Joe Elder               Berkley Pub Group                         2
...                                                                                                                ...
Zia                                                Scott O'Dell            Laurel-Leaf Books                         2
                                                                           Yearling Books                            2
Zimmermann Telegram                                Barbara Tuchman         Ballantine Books                          2
Zoids Chaotic Century (Zoids: Chaotic Century (... Michiro Ueyama          Viz Comics                                4
Ã?Ã?berleben in der WÃ?ÃÂ¼ste Danakil.         RÃ?ÃÂ¼diger Nehberg   Piper                                     2

                                                                                                           Image-URL-M  \
Book-Title                                         Book-Author             Publisher
!%@ (A Nutshell handbook)                          Donnalyn Frey           O'Reilly                                  2
'A Hell of a Place to Lose a Cow': An American ... Tim Brookes             National Geographic                       2
10,000 dreams interpreted: A dictionary of dreams  Gustavus Hindman Miller Barnes &amp; Nobles Books                 2
101 Famous Poems                                   Roy J. Cook             McGraw-Hill/Contemporary Books            3
15 Houseplants Even You Can't Kill                 Joe Elder               Berkley Pub Group                         2
...                                                                                                                ...
Zia                                                Scott O'Dell            Laurel-Leaf Books                         2
                                                                           Yearling Books                            2
Zimmermann Telegram                                Barbara Tuchman         Ballantine Books                          2
Zoids Chaotic Century (Zoids: Chaotic Century (... Michiro Ueyama          Viz Comics                                4
Ã?Ã?berleben in der WÃ?ÃÂ¼ste Danakil.         RÃ?ÃÂ¼diger Nehberg   Piper                                     2

                                                                                                           Image-URL-L  \
Book-Title                                         Book-Author             Publisher
!%@ (A Nutshell handbook)                          Donnalyn Frey           O'Reilly                                  2
'A Hell of a Place to Lose a Cow': An American ... Tim Brookes             National Geographic                       2
10,000 dreams interpreted: A dictionary of dreams  Gustavus Hindman Miller Barnes &amp; Nobles Books                 2
101 Famous Poems                                   Roy J. Cook             McGraw-Hill/Contemporary Books            3
15 Houseplants Even You Can't Kill                 Joe Elder               Berkley Pub Group                         2
...                                                                                                                ...
Zia                                                Scott O'Dell            Laurel-Leaf Books                         2
                                                                           Yearling Books                            2
Zimmermann Telegram                                Barbara Tuchman         Ballantine Books                          2
Zoids Chaotic Century (Zoids: Chaotic Century (... Michiro Ueyama          Viz Comics                                4
Ã?Ã?berleben in der WÃ?ÃÂ¼ste Danakil.         RÃ?ÃÂ¼diger Nehberg   Piper                                     2

                                                                                                           Book-Rating
Book-Title                                         Book-Author             Publisher
!%@ (A Nutshell handbook)                          Donnalyn Frey           O'Reilly                                  2
'A Hell of a Place to Lose a Cow': An American ... Tim Brookes             National Geographic                       2
10,000 dreams interpreted: A dictionary of dreams  Gustavus Hindman Miller Barnes &amp; Nobles Books                 2
101 Famous Poems                                   Roy J. Cook             McGraw-Hill/Contemporary Books            3
15 Houseplants Even You Can't Kill                 Joe Elder               Berkley Pub Group                         2
...                                                                                                                ...
Zia                                                Scott O'Dell            Laurel-Leaf Books                         2
                                                                           Yearling Books                            2
Zimmermann Telegram                                Barbara Tuchman         Ballantine Books                          2
Zoids Chaotic Century (Zoids: Chaotic Century (... Michiro Ueyama          Viz Comics                                4
Ã?Ã?berleben in der WÃ?ÃÂ¼ste Danakil.         RÃ?ÃÂ¼diger Nehberg   Piper                                     2

[4725 rows x 6 columns]

### 5. For each book in `merged books` compute its average rating.

The average is computed considering all books in `books` that have been merged.

In [273]:
### Calcolo prima la media su tutti i libri e poi effettuo il merge con il dataset merged books con l'informazione aggiuntiva della media voto
group_rating = df_books.groupby(['Book-Title' , 'Book-Author' , 'Publisher'], as_index = False)

In [274]:
group_rating = group_rating["Book-Rating"].mean()

In [275]:
merged_books.head()

                                                                                                           ISBN  \
Book-Title                                         Book-Author             Publisher
!%@ (A Nutshell handbook)                          Donnalyn Frey           O'Reilly                           2
'A Hell of a Place to Lose a Cow': An American ... Tim Brookes             National Geographic                2
10,000 dreams interpreted: A dictionary of dreams  Gustavus Hindman Miller Barnes &amp; Nobles Books          2
101 Famous Poems                                   Roy J. Cook             McGraw-Hill/Contemporary Books     3
15 Houseplants Even You Can't Kill                 Joe Elder               Berkley Pub Group                  2
...                                                                                                         ...
Zia                                                Scott O'Dell            Laurel-Leaf Books                  2
                                                                           Yearling Books                     2
Zimmermann Telegram                                Barbara Tuchman         Ballantine Books                   2
Zoids Chaotic Century (Zoids: Chaotic Century (... Michiro Ueyama          Viz Comics                         4
Ã?Ã?berleben in der WÃ?ÃÂ¼ste Danakil.         RÃ?ÃÂ¼diger Nehberg   Piper                              2

                                                                                                           Year-Of-Publication  \
Book-Title                                         Book-Author             Publisher
!%@ (A Nutshell handbook)                          Donnalyn Frey           O'Reilly                                          2
'A Hell of a Place to Lose a Cow': An American ... Tim Brookes             National Geographic                               2
10,000 dreams interpreted: A dictionary of dreams  Gustavus Hindman Miller Barnes &amp; Nobles Books                         2
101 Famous Poems                                   Roy J. Cook             McGraw-Hill/Contemporary Books                    3
15 Houseplants Even You Can't Kill                 Joe Elder               Berkley Pub Group                                 2
...                                                                                                                        ...
Zia                                                Scott O'Dell            Laurel-Leaf Books                                 2
                                                                           Yearling Books                                    2
Zimmermann Telegram                                Barbara Tuchman         Ballantine Books                                  2
Zoids Chaotic Century (Zoids: Chaotic Century (... Michiro Ueyama          Viz Comics                                        4
Ã?Ã?berleben in der WÃ?ÃÂ¼ste Danakil.         RÃ?ÃÂ¼diger Nehberg   Piper                                             2

                                                                                                           Image-URL-S  \
Book-Title                                         Book-Author             Publisher
!%@ (A Nutshell handbook)                          Donnalyn Frey           O'Reilly                                  2
'A Hell of a Place to Lose a Cow': An American ... Tim Brookes             National Geographic                       2
10,000 dreams interpreted: A dictionary of dreams  Gustavus Hindman Miller Barnes &amp; Nobles Books                 2
101 Famous Poems                                   Roy J. Cook             McGraw-Hill/Contemporary Books            3
15 Houseplants Even You Can't Kill                 Joe Elder               Berkley Pub Group                         2
...                                                                                                                ...
Zia                                                Scott O'Dell            Laurel-Leaf Books                         2
                                                                           Yearling Books                            2
Zimmermann Telegram                                Barbara Tuchman         Ballantine Books                          2
Zoids Chaotic Century (Zoids: Chaotic Century (... Michiro Ueyama          Viz Comics                                4
Ã?Ã?berleben in der WÃ?ÃÂ¼ste Danakil.         RÃ?ÃÂ¼diger Nehberg   Piper                                     2

                                                                                                           Image-URL-M  \
Book-Title                                         Book-Author             Publisher
!%@ (A Nutshell handbook)                          Donnalyn Frey           O'Reilly                                  2
'A Hell of a Place to Lose a Cow': An American ... Tim Brookes             National Geographic                       2
10,000 dreams interpreted: A dictionary of dreams  Gustavus Hindman Miller Barnes &amp; Nobles Books                 2
101 Famous Poems                                   Roy J. Cook             McGraw-Hill/Contemporary Books            3
15 Houseplants Even You Can't Kill                 Joe Elder               Berkley Pub Group                         2
...                                                                                                                ...
Zia                                                Scott O'Dell            Laurel-Leaf Books                         2
                                                                           Yearling Books                            2
Zimmermann Telegram                                Barbara Tuchman         Ballantine Books                          2
Zoids Chaotic Century (Zoids: Chaotic Century (... Michiro Ueyama          Viz Comics                                4
Ã?Ã?berleben in der WÃ?ÃÂ¼ste Danakil.         RÃ?ÃÂ¼diger Nehberg   Piper                                     2

                                                                                                           Image-URL-L  \
Book-Title                                         Book-Author             Publisher
!%@ (A Nutshell handbook)                          Donnalyn Frey           O'Reilly                                  2
'A Hell of a Place to Lose a Cow': An American ... Tim Brookes             National Geographic                       2
10,000 dreams interpreted: A dictionary of dreams  Gustavus Hindman Miller Barnes &amp; Nobles Books                 2
101 Famous Poems                                   Roy J. Cook             McGraw-Hill/Contemporary Books            3
15 Houseplants Even You Can't Kill                 Joe Elder               Berkley Pub Group                         2
...                                                                                                                ...
Zia                                                Scott O'Dell            Laurel-Leaf Books                         2
                                                                           Yearling Books                            2
Zimmermann Telegram                                Barbara Tuchman         Ballantine Books                          2
Zoids Chaotic Century (Zoids: Chaotic Century (... Michiro Ueyama          Viz Comics                                4
Ã?Ã?berleben in der WÃ?ÃÂ¼ste Danakil.         RÃ?ÃÂ¼diger Nehberg   Piper                                     2

                                                                                                           Book-Rating
Book-Title                                         Book-Author             Publisher
!%@ (A Nutshell handbook)                          Donnalyn Frey           O'Reilly                                  2
'A Hell of a Place to Lose a Cow': An American ... Tim Brookes             National Geographic                       2
10,000 dreams interpreted: A dictionary of dreams  Gustavus Hindman Miller Barnes &amp; Nobles Books                 2
101 Famous Poems                                   Roy J. Cook             McGraw-Hill/Contemporary Books            3
15 Houseplants Even You Can't Kill                 Joe Elder               Berkley Pub Group                         2
...                                                                                                                ...
Zia                                                Scott O'Dell            Laurel-Leaf Books                         2
                                                                           Yearling Books                            2
Zimmermann Telegram                                Barbara Tuchman         Ballantine Books                          2
Zoids Chaotic Century (Zoids: Chaotic Century (... Michiro Ueyama          Viz Comics                                4
Ã?Ã?berleben in der WÃ?ÃÂ¼ste Danakil.         RÃ?ÃÂ¼diger Nehberg   Piper                                     2

[4725 rows x 6 columns]

In [276]:
group_rating.head()

,Book-Title,Book-Author,Publisher,Book-Rating
0,A Light in the Storm: The Civil War Diary of ...,Karen Hesse,Hyperion Books for Children,2.250000
1,Always Have Popsicles,Rebecca Harvin,Rebecca L. Harvin,0.000000
2,Apple Magic (The Collector's series),Martina Boudreau,Amer Cooking Guild,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",Nancy N. Rue,Zonderkidz,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,Lou Mobley,"Teleonet, Incorporated",0.000000
...,...,...,...,...
266122,Ã?Ã?lpiraten.,Janwillem van de Wetering,Rowohlt Tb.,0.000000
266123,Ã?Ã?rger mit Produkt X. Roman.,Joan Aiken,Diogenes Verlag,5.250000
266124,Ã?Ã?sterlich leben.,Anselm GrÃ?ÃÂ¼n,"Herder, Freiburg",7.000000
266125,Ã?Ã?stlich der Berge.,David Guterson,btb,2.666667
266126,Ã?Ã?thique en toc,Didier Daeninckx,Baleine,4.000000

In [277]:
### Sistemo il dataset droppando le colonne inutili
merged_books = merged_books.copy(deep=True)
merged_books['Copy_Count'] = merged_books['ISBN']
merged_books.drop('Year-Of-Publication', inplace=True , axis=1)
merged_books.drop('Image-URL-L', inplace=True , axis=1)
merged_books.drop('Image-URL-M', inplace=True , axis=1)
merged_books.drop('Image-URL-S', inplace=True , axis=1)
merged_books.drop('Book-Rating', inplace=True , axis=1)
merged_books.drop('ISBN', inplace=True , axis=1)

In [278]:
merged_books = pd.merge(merged_books , group_rating , how='left' , on=['Book-Title' , 'Book-Author' , 'Publisher'])

In [279]:
merged_books.head()

,Book-Title,Book-Author,Publisher,Copy_Count,Book-Rating
0,!%@ (A Nutshell handbook),Donnalyn Frey,O'Reilly,2,3.000000
1,'A Hell of a Place to Lose a Cow': An American...,Tim Brookes,National Geographic,2,1.700000
2,"10,000 dreams interpreted: A dictionary of dreams",Gustavus Hindman Miller,Barnes &amp; Nobles Books,2,6.958333
3,101 Famous Poems,Roy J. Cook,McGraw-Hill/Contemporary Books,3,3.111111
4,15 Houseplants Even You Can't Kill,Joe Elder,Berkley Pub Group,2,0.000000
...,...,...,...,...,...
4720,Zia,Scott O'Dell,Laurel-Leaf Books,2,2.547619
4721,Zia,Scott O'Dell,Yearling Books,2,1.000000
4722,Zimmermann Telegram,Barbara Tuchman,Ballantine Books,2,2.000000
4723,Zoids Chaotic Century (Zoids: Chaotic Century ...,Michiro Ueyama,Viz Comics,4,10.000000
4724,Ã?Ã?berleben in der WÃ?ÃÂ¼ste Danakil.,RÃ?ÃÂ¼diger Nehberg,Piper,2,3.833333

### 6. For each book in `merged books` compute the minimum and maximum of the average ratings over all corresponding books in the `books` dataset.

Hence for each book in `merged books` we will have exactly two values (a minimum and a maximum)

In [280]:
### Recupero il minimo rating per ogni libro e successivamente effettuo left join tra questo raggruppamento e merged_books
group_rating = df_books.groupby(['Book-Title' , 'Book-Author' , 'Publisher'], as_index = False)

In [281]:
group_rating = group_rating["Book-Rating"].min()

In [282]:
group_rating.head()

,Book-Title,Book-Author,Publisher,Book-Rating
0,A Light in the Storm: The Civil War Diary of ...,Karen Hesse,Hyperion Books for Children,2.250000
1,Always Have Popsicles,Rebecca Harvin,Rebecca L. Harvin,0.000000
2,Apple Magic (The Collector's series),Martina Boudreau,Amer Cooking Guild,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",Nancy N. Rue,Zonderkidz,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,Lou Mobley,"Teleonet, Incorporated",0.000000
...,...,...,...,...
266122,Ã?Ã?lpiraten.,Janwillem van de Wetering,Rowohlt Tb.,0.000000
266123,Ã?Ã?rger mit Produkt X. Roman.,Joan Aiken,Diogenes Verlag,5.250000
266124,Ã?Ã?sterlich leben.,Anselm GrÃ?ÃÂ¼n,"Herder, Freiburg",7.000000
266125,Ã?Ã?stlich der Berge.,David Guterson,btb,2.666667
266126,Ã?Ã?thique en toc,Didier Daeninckx,Baleine,4.000000

In [283]:
group_rating['Min-Rating']= group_rating['Book-Rating']
group_rating.drop('Book-Rating', inplace=True , axis=1)

In [284]:
merged_books = pd.merge(merged_books, group_rating, how='left', on=['Book-Title', 'Book-Author', 'Publisher'])
merged_books.head()

,Book-Title,Book-Author,Publisher,Copy_Count,Book-Rating,Min-Rating
0,!%@ (A Nutshell handbook),Donnalyn Frey,O'Reilly,2,3.000000,0.000000
1,'A Hell of a Place to Lose a Cow': An American...,Tim Brookes,National Geographic,2,1.700000,0.000000
2,"10,000 dreams interpreted: A dictionary of dreams",Gustavus Hindman Miller,Barnes &amp; Nobles Books,2,6.958333,6.666667
3,101 Famous Poems,Roy J. Cook,McGraw-Hill/Contemporary Books,3,3.111111,0.000000
4,15 Houseplants Even You Can't Kill,Joe Elder,Berkley Pub Group,2,0.000000,0.000000
...,...,...,...,...,...,...
4720,Zia,Scott O'Dell,Laurel-Leaf Books,2,2.547619,1.666667
4721,Zia,Scott O'Dell,Yearling Books,2,1.000000,0.000000
4722,Zimmermann Telegram,Barbara Tuchman,Ballantine Books,2,2.000000,0.000000
4723,Zoids Chaotic Century (Zoids: Chaotic Century ...,Michiro Ueyama,Viz Comics,4,10.000000,10.000000
4724,Ã?Ã?berleben in der WÃ?ÃÂ¼ste Danakil.,RÃ?ÃÂ¼diger Nehberg,Piper,2,3.833333,2.666667

In [285]:
### Recupero il massimo rating per ogni libro e successivamente effettuo left join tra questo raggruppamento e merged_books
group_rating = df_books.groupby(['Book-Title', 'Book-Author', 'Publisher'], as_index=False)
group_rating = group_rating["Book-Rating"].max()
group_rating.head()

,Book-Title,Book-Author,Publisher,Book-Rating
0,A Light in the Storm: The Civil War Diary of ...,Karen Hesse,Hyperion Books for Children,2.250000
1,Always Have Popsicles,Rebecca Harvin,Rebecca L. Harvin,0.000000
2,Apple Magic (The Collector's series),Martina Boudreau,Amer Cooking Guild,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",Nancy N. Rue,Zonderkidz,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,Lou Mobley,"Teleonet, Incorporated",0.000000
...,...,...,...,...
266122,Ã?Ã?lpiraten.,Janwillem van de Wetering,Rowohlt Tb.,0.000000
266123,Ã?Ã?rger mit Produkt X. Roman.,Joan Aiken,Diogenes Verlag,5.250000
266124,Ã?Ã?sterlich leben.,Anselm GrÃ?ÃÂ¼n,"Herder, Freiburg",7.000000
266125,Ã?Ã?stlich der Berge.,David Guterson,btb,2.666667
266126,Ã?Ã?thique en toc,Didier Daeninckx,Baleine,4.000000

In [286]:
group_rating['Max-Rating']= group_rating['Book-Rating']
group_rating.drop('Book-Rating', inplace=True , axis=1)

In [287]:
merged_books = pd.merge(merged_books, group_rating, how='left', on=['Book-Title', 'Book-Author', 'Publisher'])
merged_books.head()

,Book-Title,Book-Author,Publisher,Copy_Count,Book-Rating,Min-Rating,Max-Rating
0,!%@ (A Nutshell handbook),Donnalyn Frey,O'Reilly,2,3.000000,0.000000,6.000000
1,'A Hell of a Place to Lose a Cow': An American...,Tim Brookes,National Geographic,2,1.700000,0.000000,3.400000
2,"10,000 dreams interpreted: A dictionary of dreams",Gustavus Hindman Miller,Barnes &amp; Nobles Books,2,6.958333,6.666667,7.250000
3,101 Famous Poems,Roy J. Cook,McGraw-Hill/Contemporary Books,3,3.111111,0.000000,5.000000
4,15 Houseplants Even You Can't Kill,Joe Elder,Berkley Pub Group,2,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...
4720,Zia,Scott O'Dell,Laurel-Leaf Books,2,2.547619,1.666667,3.428571
4721,Zia,Scott O'Dell,Yearling Books,2,1.000000,0.000000,2.000000
4722,Zimmermann Telegram,Barbara Tuchman,Ballantine Books,2,2.000000,0.000000,4.000000
4723,Zoids Chaotic Century (Zoids: Chaotic Century ...,Michiro Ueyama,Viz Comics,4,10.000000,10.000000,10.000000
4724,Ã?Ã?berleben in der WÃ?ÃÂ¼ste Danakil.,RÃ?ÃÂ¼diger Nehberg,Piper,2,3.833333,2.666667,5.000000

### 7. For each book in `goodbooks`, compute the list of its authors. Assuming that the number of reviews with a text (column `work_text_reviews_count`) is split equally among all authors, find for each authors the total number of reviews with a text. We will call this quantity the *shared number of reviews with a text*.

In [288]:
### Costruisco una lista di autori splittando la colonna author_list
df_goodbooks['author_list'] = df_goodbooks.authors.apply(lambda x: x.split(','))

In [289]:
df_goodbooks.head()

,book_id,goodreads_book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,title,language_code,average_rating,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url,avg_rating,author_list
0,1,2767052,2767052,2792775,272,439023483,9.78043902348e+12,Suzanne Collins,2008.0,The Hunger Games,"The Hunger Games (The Hunger Games, #1)",eng,4.34,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,4.341984,[Suzanne Collins]
1,2,3,3,4640799,491,439554934,9.78043955493e+12,"J.K. Rowling, Mary GrandPrÃ©",1997.0,Harry Potter and the Philosopher's Stone,Harry Potter and the Sorcerer's Stone (Harry P...,eng,4.44,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...,4.443047,"[J.K. Rowling, Mary GrandPrÃ©]"
2,3,41865,41865,3212258,226,316015849,9.78031601584e+12,Stephenie Meyer,2005.0,Twilight,"Twilight (Twilight, #1)",en-US,3.57,3866839,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...,3.571067,[Stephenie Meyer]
3,4,2657,2657,3275794,487,61120081,9.78006112008e+12,Harper Lee,1960.0,To Kill a Mockingbird,To Kill a Mockingbird,eng,4.25,3198671,3340896,72586,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...,4.254818,[Harper Lee]
4,5,4671,4671,245494,1356,743273567,9.78074327356e+12,F. Scott Fitzgerald,1925.0,The Great Gatsby,The Great Gatsby,eng,3.89,2683664,2773745,51992,86236,197621,606158,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...,3.887376,[F. Scott Fitzgerald]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,95,5297,5297,1858012,2303,375751513,9.78037575152e+12,"Oscar Wilde, Jeffrey Eugenides",1891.0,The Picture of Dorian Gray,The Picture of Dorian Gray,eng,4.06,590014,674551,19647,9825,30735,129420,246892,257679,https://images.gr-assets.com/books/1424596966m...,https://images.gr-assets.com/books/1424596966s...,4.055317,"[Oscar Wilde, Jeffrey Eugenides]"
95,96,13536860,13536860,18034963,133,345803507,9.7803458035e+12,E.L. James,2012.0,Fifty Shades Freed,"Fifty Shades Freed (Fifty Shades, #3)",eng,3.88,387290,610116,25287,39079,55691,109963,140304,265079,https://images.gr-assets.com/books/1336418837m...,https://images.gr-assets.com/books/1336418837s...,3.879526,[E.L. James]
96,97,17245,17245,3165724,2207,393970124,9.78039397013e+12,"Bram Stoker, Nina Auerbach, David J. Skal",1897.0,Dracula,Dracula,eng,3.98,618973,689739,17263,11756,36719,151396,246043,243825,https://images.gr-assets.com/books/1387151694m...,https://images.gr-assets.com/books/1387151694s...,3.976401,"[Bram Stoker, Nina Auerbach, David J. Skal]"
97,98,5060378,5060378,6976108,209,307269981,9.78030726998e+12,"Stieg Larsson, Reg Keeland",2006.0,Flickan som lekte med elden,"The Girl Who Played with Fire (Millennium, #2)",eng,4.22,563994,649253,31423,4623,15781,91021,258236,279592,https://images.gr-assets.com/books/1351778881m...,https://images.gr-assets.com/books/1351778881s...,4.220469,"[Stieg Larsson, Reg Keeland]"
98,99,11857408,11857408,16813814,147,1612130585,9.78161213058e+12,E.L. James,2011.0,Fifty Shades Darker,"Fifty Shades Darker (Fifty Shades, #2)",eng,3.87,552059,623340,28052,37245,58935,114203,150906,262051,https://images.gr-assets.com/books/1358266080m...,https://images.gr-assets.com/books/1358266080s...,3.868840,[E.L. James]

In [290]:
### Calcolo il numero di autori per libro
df_goodbooks['author_number'] = df_goodbooks.author_list.apply(lambda  x:len(x))

In [291]:
df_goodbooks['work_text_reviews_count'] = df_goodbooks['work_text_reviews_count'].astype(int)

In [292]:
### Calcolo la quota di recensioni condivise
df_goodbooks['shared_number'] = df_goodbooks['work_text_reviews_count'] / df_goodbooks['author_number']

In [293]:
df_goodbooks.head()

,book_id,goodreads_book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,title,language_code,average_rating,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url,avg_rating,author_list,author_number,shared_number
0,1,2767052,2767052,2792775,272,439023483,9.78043902348e+12,Suzanne Collins,2008.0,The Hunger Games,"The Hunger Games (The Hunger Games, #1)",eng,4.34,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,4.341984,[Suzanne Collins],1,155254.000000
1,2,3,3,4640799,491,439554934,9.78043955493e+12,"J.K. Rowling, Mary GrandPrÃ©",1997.0,Harry Potter and the Philosopher's Stone,Harry Potter and the Sorcerer's Stone (Harry P...,eng,4.44,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...,4.443047,"[J.K. Rowling, Mary GrandPrÃ©]",2,37933.500000
2,3,41865,41865,3212258,226,316015849,9.78031601584e+12,Stephenie Meyer,2005.0,Twilight,"Twilight (Twilight, #1)",en-US,3.57,3866839,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...,3.571067,[Stephenie Meyer],1,95009.000000
3,4,2657,2657,3275794,487,61120081,9.78006112008e+12,Harper Lee,1960.0,To Kill a Mockingbird,To Kill a Mockingbird,eng,4.25,3198671,3340896,72586,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...,4.254818,[Harper Lee],1,72586.000000
4,5,4671,4671,245494,1356,743273567,9.78074327356e+12,F. Scott Fitzgerald,1925.0,The Great Gatsby,The Great Gatsby,eng,3.89,2683664,2773745,51992,86236,197621,606158,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...,3.887376,[F. Scott Fitzgerald],1,51992.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,95,5297,5297,1858012,2303,375751513,9.78037575152e+12,"Oscar Wilde, Jeffrey Eugenides",1891.0,The Picture of Dorian Gray,The Picture of Dorian Gray,eng,4.06,590014,674551,19647,9825,30735,129420,246892,257679,https://images.gr-assets.com/books/1424596966m...,https://images.gr-assets.com/books/1424596966s...,4.055317,"[Oscar Wilde, Jeffrey Eugenides]",2,9823.500000
95,96,13536860,13536860,18034963,133,345803507,9.7803458035e+12,E.L. James,2012.0,Fifty Shades Freed,"Fifty Shades Freed (Fifty Shades, #3)",eng,3.88,387290,610116,25287,39079,55691,109963,140304,265079,https://images.gr-assets.com/books/1336418837m...,https://images.gr-assets.com/books/1336418837s...,3.879526,[E.L. James],1,25287.000000
96,97,17245,17245,3165724,2207,393970124,9.78039397013e+12,"Bram Stoker, Nina Auerbach, David J. Skal",1897.0,Dracula,Dracula,eng,3.98,618973,689739,17263,11756,36719,151396,246043,243825,https://images.gr-assets.com/books/1387151694m...,https://images.gr-assets.com/books/1387151694s...,3.976401,"[Bram Stoker, Nina Auerbach, David J. Skal]",3,5754.333333
97,98,5060378,5060378,6976108,209,307269981,9.78030726998e+12,"Stieg Larsson, Reg Keeland",2006.0,Flickan som lekte med elden,"The Girl Who Played with Fire (Millennium, #2)",eng,4.22,563994,649253,31423,4623,15781,91021,258236,279592,https://images.gr-assets.com/books/1351778881m...,https://images.gr-assets.com/books/1351778881s...,4.220469,"[Stieg Larsson, Reg Keeland]",2,15711.500000
98,99,11857408,11857408,16813814,147,1612130585,9.78161213058e+12,E.L. James,2011.0,Fifty Shades Darker,"Fifty Shades Darker (Fifty Shades, #2)",eng,3.87,552059,623340,28052,37245,58935,114203,150906,262051,https://images.gr-assets.com/books/1358266080m...,https://images.gr-assets.com/books/1358266080s...,3.868840,[E.L. James],1,28052.000000

In [294]:
### Esplodo il dataset per ottenere per ogni libro un singolo autore e non più la lista di autori
l = df_goodbooks.apply(pd.Series.explode).reset_index()
l.head()

,index,book_id,goodreads_book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,title,language_code,average_rating,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url,avg_rating,author_list,author_number,shared_number
0,0,1,2767052,2767052,2792775,272,439023483,9.78043902348e+12,Suzanne Collins,2008.0,The Hunger Games,"The Hunger Games (The Hunger Games, #1)",eng,4.34,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,4.341984,Suzanne Collins,1,155254.000000
1,1,2,3,3,4640799,491,439554934,9.78043955493e+12,"J.K. Rowling, Mary GrandPrÃ©",1997.0,Harry Potter and the Philosopher's Stone,Harry Potter and the Sorcerer's Stone (Harry P...,eng,4.44,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...,4.443047,J.K. Rowling,2,37933.500000
2,1,2,3,3,4640799,491,439554934,9.78043955493e+12,"J.K. Rowling, Mary GrandPrÃ©",1997.0,Harry Potter and the Philosopher's Stone,Harry Potter and the Sorcerer's Stone (Harry P...,eng,4.44,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...,4.443047,Mary GrandPrÃ©,2,37933.500000
3,2,3,41865,41865,3212258,226,316015849,9.78031601584e+12,Stephenie Meyer,2005.0,Twilight,"Twilight (Twilight, #1)",en-US,3.57,3866839,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...,3.571067,Stephenie Meyer,1,95009.000000
4,3,4,2657,2657,3275794,487,61120081,9.78006112008e+12,Harper Lee,1960.0,To Kill a Mockingbird,To Kill a Mockingbird,eng,4.25,3198671,3340896,72586,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...,4.254818,Harper Lee,1,72586.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,96,97,17245,17245,3165724,2207,393970124,9.78039397013e+12,"Bram Stoker, Nina Auerbach, David J. Skal",1897.0,Dracula,Dracula,eng,3.98,618973,689739,17263,11756,36719,151396,246043,243825,https://images.gr-assets.com/books/1387151694m...,https://images.gr-assets.com/books/1387151694s...,3.976401,Nina Auerbach,3,5754.333333
137,96,97,17245,17245,3165724,2207,393970124,9.78039397013e+12,"Bram Stoker, Nina Auerbach, David J. Skal",1897.0,Dracula,Dracula,eng,3.98,618973,689739,17263,11756,36719,151396,246043,243825,https://images.gr-assets.com/books/1387151694m...,https://images.gr-assets.com/books/1387151694s...,3.976401,David J. Skal,3,5754.333333
138,97,98,5060378,5060378,6976108,209,307269981,9.78030726998e+12,"Stieg Larsson, Reg Keeland",2006.0,Flickan som lekte med elden,"The Girl Who Played with Fire (Millennium, #2)",eng,4.22,563994,649253,31423,4623,15781,91021,258236,279592,https://images.gr-assets.com/books/1351778881m...,https://images.gr-assets.com/books/1351778881s...,4.220469,Stieg Larsson,2,15711.500000
139,97,98,5060378,5060378,6976108,209,307269981,9.78030726998e+12,"Stieg Larsson, Reg Keeland",2006.0,Flickan som lekte med elden,"The Girl Who Played with Fire (Millennium, #2)",eng,4.22,563994,649253,31423,4623,15781,91021,258236,279592,https://images.gr-assets.com/books/1351778881m...,https://images.gr-assets.com/books/1351778881s...,4.220469,Reg Keeland,2,15711.500000
140,98,99,11857408,11857408,16813814,147,1612130585,9.78161213058e+12,E.L. James,2011.0,Fifty Shades Darker,"Fifty Shades Darker (Fifty Shades, #2)",eng,3.87,552059,623340,28052,37245,58935,114203,150906,262051,https://images.gr-assets.com/books/1358266080m...,https://images.gr-assets.com/books/1358266080s...,3.868840,E.L. James,1,28052.000000

In [295]:
group_autori= l.groupby(['author_list'], as_index=False)
group_autori = group_autori["shared_number"].sum()
group_autori.head()

                  author_list  shared_number
0              Alan R. Clarke   27890.500000
1     B.M. Mooyaart-Doubleday    6941.666667
2                Bernard Knox    1620.200000
3               CelÃ¢l Ãster   15172.666667
4               David J. Skal    5754.333333
..                        ...            ...
105             Veronica Roth  156896.000000
106           William Golding   26886.000000
107           William Goldman   15630.000000
108       William Shakespeare    7389.000000
109               Yann Martel   42962.000000

[110 rows x 2 columns]

### 8. For each year of publication, determine the author that has the largest value of the shared number of reviews with a text.

In [296]:
df_goodbooks.head()

,book_id,goodreads_book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,title,language_code,average_rating,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url,avg_rating,author_list,author_number,shared_number
0,1,2767052,2767052,2792775,272,439023483,9.78043902348e+12,Suzanne Collins,2008.0,The Hunger Games,"The Hunger Games (The Hunger Games, #1)",eng,4.34,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,4.341984,[Suzanne Collins],1,155254.000000
1,2,3,3,4640799,491,439554934,9.78043955493e+12,"J.K. Rowling, Mary GrandPrÃ©",1997.0,Harry Potter and the Philosopher's Stone,Harry Potter and the Sorcerer's Stone (Harry P...,eng,4.44,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...,4.443047,"[J.K. Rowling, Mary GrandPrÃ©]",2,37933.500000
2,3,41865,41865,3212258,226,316015849,9.78031601584e+12,Stephenie Meyer,2005.0,Twilight,"Twilight (Twilight, #1)",en-US,3.57,3866839,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...,3.571067,[Stephenie Meyer],1,95009.000000
3,4,2657,2657,3275794,487,61120081,9.78006112008e+12,Harper Lee,1960.0,To Kill a Mockingbird,To Kill a Mockingbird,eng,4.25,3198671,3340896,72586,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...,4.254818,[Harper Lee],1,72586.000000
4,5,4671,4671,245494,1356,743273567,9.78074327356e+12,F. Scott Fitzgerald,1925.0,The Great Gatsby,The Great Gatsby,eng,3.89,2683664,2773745,51992,86236,197621,606158,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...,3.887376,[F. Scott Fitzgerald],1,51992.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,95,5297,5297,1858012,2303,375751513,9.78037575152e+12,"Oscar Wilde, Jeffrey Eugenides",1891.0,The Picture of Dorian Gray,The Picture of Dorian Gray,eng,4.06,590014,674551,19647,9825,30735,129420,246892,257679,https://images.gr-assets.com/books/1424596966m...,https://images.gr-assets.com/books/1424596966s...,4.055317,"[Oscar Wilde, Jeffrey Eugenides]",2,9823.500000
95,96,13536860,13536860,18034963,133,345803507,9.7803458035e+12,E.L. James,2012.0,Fifty Shades Freed,"Fifty Shades Freed (Fifty Shades, #3)",eng,3.88,387290,610116,25287,39079,55691,109963,140304,265079,https://images.gr-assets.com/books/1336418837m...,https://images.gr-assets.com/books/1336418837s...,3.879526,[E.L. James],1,25287.000000
96,97,17245,17245,3165724,2207,393970124,9.78039397013e+12,"Bram Stoker, Nina Auerbach, David J. Skal",1897.0,Dracula,Dracula,eng,3.98,618973,689739,17263,11756,36719,151396,246043,243825,https://images.gr-assets.com/books/1387151694m...,https://images.gr-assets.com/books/1387151694s...,3.976401,"[Bram Stoker, Nina Auerbach, David J. Skal]",3,5754.333333
97,98,5060378,5060378,6976108,209,307269981,9.78030726998e+12,"Stieg Larsson, Reg Keeland",2006.0,Flickan som lekte med elden,"The Girl Who Played with Fire (Millennium, #2)",eng,4.22,563994,649253,31423,4623,15781,91021,258236,279592,https://images.gr-assets.com/books/1351778881m...,https://images.gr-assets.com/books/1351778881s...,4.220469,"[Stieg Larsson, Reg Keeland]",2,15711.500000
98,99,11857408,11857408,16813814,147,1612130585,9.78161213058e+12,E.L. James,2011.0,Fifty Shades Darker,"Fifty Shades Darker (Fifty Shades, #2)",eng,3.87,552059,623340,28052,37245,58935,114203,150906,262051,https://images.gr-assets.com/books/1358266080m...,https://images.gr-assets.com/books/1358266080s...,3.868840,[E.L. James],1,28052.000000

In [297]:
l = df_goodbooks.apply(pd.Series.explode).reset_index()
l.head()

,index,book_id,goodreads_book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,title,language_code,average_rating,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url,avg_rating,author_list,author_number,shared_number
0,0,1,2767052,2767052,2792775,272,439023483,9.78043902348e+12,Suzanne Collins,2008.0,The Hunger Games,"The Hunger Games (The Hunger Games, #1)",eng,4.34,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,4.341984,Suzanne Collins,1,155254.000000
1,1,2,3,3,4640799,491,439554934,9.78043955493e+12,"J.K. Rowling, Mary GrandPrÃ©",1997.0,Harry Potter and the Philosopher's Stone,Harry Potter and the Sorcerer's Stone (Harry P...,eng,4.44,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...,4.443047,J.K. Rowling,2,37933.500000
2,1,2,3,3,4640799,491,439554934,9.78043955493e+12,"J.K. Rowling, Mary GrandPrÃ©",1997.0,Harry Potter and the Philosopher's Stone,Harry Potter and the Sorcerer's Stone (Harry P...,eng,4.44,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...,4.443047,Mary GrandPrÃ©,2,37933.500000
3,2,3,41865,41865,3212258,226,316015849,9.78031601584e+12,Stephenie Meyer,2005.0,Twilight,"Twilight (Twilight, #1)",en-US,3.57,3866839,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...,3.571067,Stephenie Meyer,1,95009.000000
4,3,4,2657,2657,3275794,487,61120081,9.78006112008e+12,Harper Lee,1960.0,To Kill a Mockingbird,To Kill a Mockingbird,eng,4.25,3198671,3340896,72586,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...,4.254818,Harper Lee,1,72586.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,96,97,17245,17245,3165724,2207,393970124,9.78039397013e+12,"Bram Stoker, Nina Auerbach, David J. Skal",1897.0,Dracula,Dracula,eng,3.98,618973,689739,17263,11756,36719,151396,246043,243825,https://images.gr-assets.com/books/1387151694m...,https://images.gr-assets.com/books/1387151694s...,3.976401,Nina Auerbach,3,5754.333333
137,96,97,17245,17245,3165724,2207,393970124,9.78039397013e+12,"Bram Stoker, Nina Auerbach, David J. Skal",1897.0,Dracula,Dracula,eng,3.98,618973,689739,17263,11756,36719,151396,246043,243825,https://images.gr-assets.com/books/1387151694m...,https://images.gr-assets.com/books/1387151694s...,3.976401,David J. Skal,3,5754.333333
138,97,98,5060378,5060378,6976108,209,307269981,9.78030726998e+12,"Stieg Larsson, Reg Keeland",2006.0,Flickan som lekte med elden,"The Girl Who Played with Fire (Millennium, #2)",eng,4.22,563994,649253,31423,4623,15781,91021,258236,279592,https://images.gr-assets.com/books/1351778881m...,https://images.gr-assets.com/books/1351778881s...,4.220469,Stieg Larsson,2,15711.500000
139,97,98,5060378,5060378,6976108,209,307269981,9.78030726998e+12,"Stieg Larsson, Reg Keeland",2006.0,Flickan som lekte med elden,"The Girl Who Played with Fire (Millennium, #2)",eng,4.22,563994,649253,31423,4623,15781,91021,258236,279592,https://images.gr-assets.com/books/1351778881m...,https://images.gr-assets.com/books/1351778881s...,4.220469,Reg Keeland,2,15711.500000
140,98,99,11857408,11857408,16813814,147,1612130585,9.78161213058e+12,E.L. James,2011.0,Fifty Shades Darker,"Fifty Shades Darker (Fifty Shades, #2)",eng,3.87,552059,623340,28052,37245,58935,114203,150906,262051,https://images.gr-assets.com/books/1358266080m...,https://images.gr-assets.com/books/1358266080s...,3.868840,E.L. James,1,28052.000000

In [298]:
### Passaggio intermedio per poter recuperare solo l'autore con il valore massimo di shared_number successivamente
group_autori= l.groupby(['original_publication_year', 'author_list'], as_index=False)
group_autori = group_autori["shared_number"].sum()
group_autori.head()

    original_publication_year         author_list  shared_number
0                      -720.0        Bernard Knox         1620.2
1                      -720.0           E.V. Rieu         1620.2
2                      -720.0   FrÃ©dÃ©ric Mugler         1620.2
3                      -720.0       Robert Fagles         1620.2
4                      -720.0               Homer         1620.2
..                        ...                 ...            ...
134                    2012.0          E.L. James        25287.0
135                    2012.0       Gillian Flynn       121614.0
136                    2012.0          John Green       140739.0
137                    2012.0       Veronica Roth        55873.0
138                    2015.0       Paula Hawkins        93600.0

[139 rows x 3 columns]

In [299]:
### Recupero la posizione per ogni anno di pubblicazione dell'autore con shared number massimo
result = group_autori.loc[group_autori.groupby(['original_publication_year'])['shared_number'].idxmax()]
result

    original_publication_year                author_list  shared_number
0                      -720.0               Bernard Knox    1620.200000
5                      1595.0   Robert           Jackson    7389.000000
7                      1811.0              Ros Ballaster    3842.000000
10                     1813.0                Jane Austen   49152.000000
11                     1818.0             Maurice Hindle    6664.333333
14                     1847.0              Michael Mason   15606.000000
18                     1859.0       Hablot Knight Browne    4364.333333
21                     1868.0          Louisa May Alcott   17090.000000
22                     1884.0               Guy Cardwell    4149.333333
25                     1891.0          Jeffrey Eugenides    9823.500000
27                     1897.0              David J. Skal    5754.333333
30                     1911.0    Frances Hodgson Burnett   13054.000000
31                     1925.0        F. Scott Fitzgerald   51992.000000
32                     1932.0              Aldous Huxley   20095.000000
33                     1936.0          Margaret Mitchell   16050.000000
34                     1937.0             J.R.R. Tolkien   37653.000000
36                     1945.0              George Orwell   35472.000000
37                     1946.0         Dom Marcos Barbosa    6134.250000
41                     1947.0    B.M. Mooyaart-Doubleday    6941.666667
44                     1949.0              CelÃ¢l Ãster   15172.666667
47                     1950.0                 C.S. Lewis   15186.000000
48                     1951.0              J.D. Salinger   44920.000000
49                     1952.0             Garth Williams    4348.000000
52                     1953.0               Ray Bradbury   30694.000000
54                     1954.0            William Golding   26886.000000
55                     1958.0              Marion Wiesel   11000.500000
57                     1960.0                 Harper Lee   72586.000000
58                     1964.0           Shel Silverstein   14368.000000
61                     1967.0                S.E. Hinton   22662.000000
62                     1969.0          Kurt Vonnegut Jr.   19646.000000
63                     1973.0            William Goldman   15630.000000
64                     1974.0           Shel Silverstein    9234.000000
65                     1977.0               Stephen King   14936.000000
66                     1979.0              Douglas Adams   20345.000000
67                     1985.0           Orson Scott Card   38054.000000
68                     1988.0             Alan R. Clarke   27890.500000
70                     1989.0               John Grisham    4239.000000
71                     1990.0           Michael Crichton    8143.000000
72                     1993.0                 Lois Lowry   54084.000000
73                     1995.0             Philip Pullman   14915.000000
74                     1996.0         George R.R. Martin   46205.000000
78                     1997.0             Mary GrandPrÃ©   37933.500000
82                     1998.0             Mary GrandPrÃ©   17086.000000
88                     1999.0            Stephen Chbosky   47116.000000
90                     2000.0                  Dan Brown   25112.000000
93                     2001.0                Yann Martel   42962.000000
94                     2002.0               Alice Sebold   36642.000000
100                    2003.0            Khaled Hosseini   59730.000000
103                    2004.0               Jodi Picoult   30719.000000
112                    2005.0            Stephenie Meyer   95009.000000
117                    2006.0                 Sara Gruen   55732.000000
121                    2007.0            Cassandra Clare   51589.000000
127                    2008.0            Suzanne Collins  155254.000000
130                    2009.0            Suzanne Collins   88538.000000
131                    2010.0            Suzanne Collins   96274.000000
132                    2011.0                 E.L. James  103489.000000
136                    2012.0                 John Green  140739.000000
138                    2015.0              Paula Hawkins   93600.000000

### 9. Assuming that there are no errors in the ISBN fields, find the books in both datasets, and compute the difference of average rating according to the ratings and the goodratings datasets

In [300]:
df_goodbooks['ISBN'] = df_goodbooks['isbn']

In [301]:
### Inner join per prendere solo i valori comuni ad entrambi i dataset
tot_books = pd.merge(df_goodbooks, df_books, how='inner', on='ISBN')
tot_books.head()

,book_id,goodreads_book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,title,language_code,average_rating,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url,avg_rating,author_list,author_number,shared_number,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,Book-Rating
0,11,77203,77203,3295919,283,1594480001,9.78159448e+12,Khaled Hosseini,2003.0,The Kite Runner,The Kite Runner,eng,4.26,1813044,1878095,59730,34288,59980,226062,628174,929591,https://images.gr-assets.com/books/1484565687m...,https://images.gr-assets.com/books/1484565687s...,4.255954,[Khaled Hosseini],1,59730.0,1594480001,The Kite Runner,Khaled Hosseini,2004,Riverhead Books,http://images.amazon.com/images/P/1594480001.0...,http://images.amazon.com/images/P/1594480001.0...,http://images.amazon.com/images/P/1594480001.0...,2.400000
1,18,5,5,2402163,376,043965548X,9.78043965548e+12,"J.K. Rowling, Mary GrandPrÃ©, Rufus Beck",1999.0,Harry Potter and the Prisoner of Azkaban,Harry Potter and the Prisoner of Azkaban (Harr...,eng,4.53,1832823,1969375,36099,6716,20413,166129,509447,1266670,https://images.gr-assets.com/books/1499277281m...,https://images.gr-assets.com/books/1499277281s...,4.527866,"[J.K. Rowling, Mary GrandPrÃ©, Rufus Beck]",3,12033.0,043965548X,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling,2004,Scholastic Paperbacks,http://images.amazon.com/images/P/043965548X.0...,http://images.amazon.com/images/P/043965548X.0...,http://images.amazon.com/images/P/043965548X.0...,3.533333
2,60,1618,1618,4259809,183,1400032717,9.78140003272e+12,Mark Haddon,2003.0,The Curious Incident of the Dog in the Night-Time,The Curious Incident of the Dog in the Night-Time,eng,3.85,867553,915790,35796,21049,58117,218218,355925,262481,https://images.gr-assets.com/books/1479863624m...,https://images.gr-assets.com/books/1479863624s...,3.852457,[Mark Haddon],1,35796.0,1400032717,The Curious Incident of the Dog in the Night-T...,Mark Haddon,2004,Vintage,http://images.amazon.com/images/P/1400032717.0...,http://images.amazon.com/images/P/1400032717.0...,http://images.amazon.com/images/P/1400032717.0...,4.813187
3,75,227443,227443,3185154,193,014028009X,9.7801402801e+12,Helen Fielding,1996.0,NaN,"Bridget Jones's Diary (Bridget Jones, #1)",eng,3.75,736498,754498,8157,28973,59309,198555,254836,212825,https://images.gr-assets.com/books/1292060045m...,https://images.gr-assets.com/books/1292060045s...,3.746498,[Helen Fielding],1,8157.0,014028009X,Bridget Jones's Diary,Helen Fielding,1999,Penguin Books,http://images.amazon.com/images/P/014028009X.0...,http://images.amazon.com/images/P/014028009X.0...,http://images.amazon.com/images/P/014028009X.0...,3.751852
4,90,231804,231804,1426690,156,014038572X,9.78014038572e+12,S.E. Hinton,1967.0,The Outsiders,The Outsiders,en-US,4.06,659248,680437,22662,10178,34346,134244,227250,274419,https://images.gr-assets.com/books/1442129426m...,https://images.gr-assets.com/books/1442129426s...,4.060180,[S.E. Hinton],1,22662.0,014038572X,The Outsiders (Now in Speak!),S. E. Hinton,1997,Puffin Books,http://images.amazon.com/images/P/014038572X.0...,http://images.amazon.com/images/P/014038572X.0...,http://images.amazon.com/images/P/014038572X.0...,4.460674

In [302]:
tot_books['diff_average_rating'] =  tot_books['Book-Rating']-tot_books['avg_rating']

In [303]:
tot_books.head()

,book_id,goodreads_book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,title,language_code,average_rating,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url,avg_rating,author_list,author_number,shared_number,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,Book-Rating,diff_average_rating
0,11,77203,77203,3295919,283,1594480001,9.78159448e+12,Khaled Hosseini,2003.0,The Kite Runner,The Kite Runner,eng,4.26,1813044,1878095,59730,34288,59980,226062,628174,929591,https://images.gr-assets.com/books/1484565687m...,https://images.gr-assets.com/books/1484565687s...,4.255954,[Khaled Hosseini],1,59730.0,1594480001,The Kite Runner,Khaled Hosseini,2004,Riverhead Books,http://images.amazon.com/images/P/1594480001.0...,http://images.amazon.com/images/P/1594480001.0...,http://images.amazon.com/images/P/1594480001.0...,2.400000,-1.855954
1,18,5,5,2402163,376,043965548X,9.78043965548e+12,"J.K. Rowling, Mary GrandPrÃ©, Rufus Beck",1999.0,Harry Potter and the Prisoner of Azkaban,Harry Potter and the Prisoner of Azkaban (Harr...,eng,4.53,1832823,1969375,36099,6716,20413,166129,509447,1266670,https://images.gr-assets.com/books/1499277281m...,https://images.gr-assets.com/books/1499277281s...,4.527866,"[J.K. Rowling, Mary GrandPrÃ©, Rufus Beck]",3,12033.0,043965548X,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling,2004,Scholastic Paperbacks,http://images.amazon.com/images/P/043965548X.0...,http://images.amazon.com/images/P/043965548X.0...,http://images.amazon.com/images/P/043965548X.0...,3.533333,-0.994533
2,60,1618,1618,4259809,183,1400032717,9.78140003272e+12,Mark Haddon,2003.0,The Curious Incident of the Dog in the Night-Time,The Curious Incident of the Dog in the Night-Time,eng,3.85,867553,915790,35796,21049,58117,218218,355925,262481,https://images.gr-assets.com/books/1479863624m...,https://images.gr-assets.com/books/1479863624s...,3.852457,[Mark Haddon],1,35796.0,1400032717,The Curious Incident of the Dog in the Night-T...,Mark Haddon,2004,Vintage,http://images.amazon.com/images/P/1400032717.0...,http://images.amazon.com/images/P/1400032717.0...,http://images.amazon.com/images/P/1400032717.0...,4.813187,0.960729
3,75,227443,227443,3185154,193,014028009X,9.7801402801e+12,Helen Fielding,1996.0,NaN,"Bridget Jones's Diary (Bridget Jones, #1)",eng,3.75,736498,754498,8157,28973,59309,198555,254836,212825,https://images.gr-assets.com/books/1292060045m...,https://images.gr-assets.com/books/1292060045s...,3.746498,[Helen Fielding],1,8157.0,014028009X,Bridget Jones's Diary,Helen Fielding,1999,Penguin Books,http://images.amazon.com/images/P/014028009X.0...,http://images.amazon.com/images/P/014028009X.0...,http://images.amazon.com/images/P/014028009X.0...,3.751852,0.005354
4,90,231804,231804,1426690,156,014038572X,9.78014038572e+12,S.E. Hinton,1967.0,The Outsiders,The Outsiders,en-US,4.06,659248,680437,22662,10178,34346,134244,227250,274419,https://images.gr-assets.com/books/1442129426m...,https://images.gr-assets.com/books/1442129426s...,4.060180,[S.E. Hinton],1,22662.0,014038572X,The Outsiders (Now in Speak!),S. E. Hinton,1997,Puffin Books,http://images.amazon.com/images/P/014038572X.0...,http://images.amazon.com/images/P/014038572X.0...,http://images.amazon.com/images/P/014038572X.0...,4.460674,0.400494

### 10. Split the users dataset according to the age. One dataset contains the users with unknown age, one with age 0-14, one with age 15-24, one with age 25-34, and so on.

In [304]:
df_users

       User-ID                            Location  Age
0            1                  nyc, new york, usa  NaN
1            2           stockton, california, usa   18
2            3     moscow, yukon territory, russia  NaN
3            4           porto, v.n.gaia, portugal   17
4            5  farnborough, hants, united kingdom  NaN
...        ...                                 ...  ...
278853  278854               portland, oregon, usa  NaN
278854  278855  tacoma, washington, united kingdom   50
278855  278856           brampton, ontario, canada  NaN
278856  278857           knoxville, tennessee, usa  NaN
278857  278858                dublin, n/a, ireland  NaN

[278858 rows x 3 columns]

In [305]:
unknown_age = df_users['Age'].isnull()
unknown_age_split = df_users[unknown_age]
unknown_age_split

       User-ID                            Location  Age
0            1                  nyc, new york, usa  NaN
2            3     moscow, yukon territory, russia  NaN
4            5  farnborough, hants, united kingdom  NaN
6            7                 washington, dc, usa  NaN
7            8            timmins, ontario, canada  NaN
...        ...                                 ...  ...
278849  278850          sergnano, lombardia, italy  NaN
278853  278854               portland, oregon, usa  NaN
278855  278856           brampton, ontario, canada  NaN
278856  278857           knoxville, tennessee, usa  NaN
278857  278858                dublin, n/a, ireland  NaN

[110762 rows x 3 columns]

In [306]:
all_age = df_users.copy(deep=True)
all_age = all_age.dropna()

In [307]:
all_age['Age'] = all_age['Age'].astype(int)

In [308]:
age_0_14 = all_age[all_age['Age'] <= 14]
age_0_14

       User-ID                           Location  Age
10          11     melbourne, victoria, australia   14
18          19                          weston, ,   14
40          41            santee, california, usa   14
119        120    villeneuve d`ascq, nord, france   13
219        220           bogota, bogota, colombia    0
...        ...                                ...  ...
278574  278575  burnaby, british columbia, canada   14
278582  278583              steele, missouri, usa   13
278668  278669          spring hill, fl, hernando   13
278751  278752        london, nova scotia, canada    9
278793  278794           st. paul, minnesota, usa   14

[4313 rows x 3 columns]

In [309]:
age_15_24 = all_age[(all_age['Age'] > 14) & ( all_age['Age'] <= 24 )]
age_15_24

       User-ID                               Location  Age
1            2              stockton, california, usa   18
3            4              porto, v.n.gaia, portugal   17
19          20           langhorne, pennsylvania, usa   19
23          24                  cologne, nrw, germany   19
27          28  freiburg, baden-wuerttemberg, germany   24
...        ...                                    ...  ...
278834  278835               karachi, sindh, pakistan   18
278837  278838                   massillon, ohio, usa   15
278845  278846               toronto, ontario, canada   23
278848  278849            georgetown, ontario, canada   23
278852  278853         stranraer, n/a, united kingdom   17

[40001 rows x 3 columns]

In [310]:
age_25_34 = all_age[(all_age['Age'] > 24) & ( all_age['Age'] <= 34 )]
age_25_34

       User-ID                                      Location  Age
9           10                    albacete, wisconsin, spain   26
12          13                   barcelona, barcelona, spain   26
17          18        rio de janeiro, rio de janeiro, brazil   25
26          27                        chicago, illinois, usa   32
32          33                   costa mesa, california, usa   34
...        ...                                           ...  ...
278832  278833  hanoi, australian capital territory, vietnam   25
278842  278843                  pismo beach, california, usa   28
278843  278844                      st. paul, minnesota, usa   28
278850  278851                            dallas, texas, usa   33
278851  278852               brisbane, queensland, australia   32

[50767 rows x 3 columns]

In [311]:
age_so_on = all_age[(all_age['Age'] > 34) ]
age_so_on

       User-ID                             Location  Age
5            6        santa monica, california, usa   61
20          21       ferrol / spain, alabama, spain   46
24          25             oakland, california, usa   55
43          44  black mountain, north carolina, usa   51
53          54                eubank, kentucky, usa   44
...        ...                                  ...  ...
278823  278824             madison, new jersey, usa   41
278831  278832       new smyrna beach, florida, usa   62
278835  278836          des moines, washington, usa   47
278839  278840           encinitas, california, usa   45
278854  278855   tacoma, washington, united kingdom   50

[73015 rows x 3 columns]

### 11. Find the books that appear only in the goodbooks datasets.

In [312]:
df_goodbooks.head()

,book_id,goodreads_book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,title,language_code,average_rating,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url,avg_rating,author_list,author_number,shared_number,ISBN
0,1,2767052,2767052,2792775,272,439023483,9.78043902348e+12,Suzanne Collins,2008.0,The Hunger Games,"The Hunger Games (The Hunger Games, #1)",eng,4.34,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,4.341984,[Suzanne Collins],1,155254.000000,439023483
1,2,3,3,4640799,491,439554934,9.78043955493e+12,"J.K. Rowling, Mary GrandPrÃ©",1997.0,Harry Potter and the Philosopher's Stone,Harry Potter and the Sorcerer's Stone (Harry P...,eng,4.44,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...,4.443047,"[J.K. Rowling, Mary GrandPrÃ©]",2,37933.500000,439554934
2,3,41865,41865,3212258,226,316015849,9.78031601584e+12,Stephenie Meyer,2005.0,Twilight,"Twilight (Twilight, #1)",en-US,3.57,3866839,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...,3.571067,[Stephenie Meyer],1,95009.000000,316015849
3,4,2657,2657,3275794,487,61120081,9.78006112008e+12,Harper Lee,1960.0,To Kill a Mockingbird,To Kill a Mockingbird,eng,4.25,3198671,3340896,72586,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...,4.254818,[Harper Lee],1,72586.000000,61120081
4,5,4671,4671,245494,1356,743273567,9.78074327356e+12,F. Scott Fitzgerald,1925.0,The Great Gatsby,The Great Gatsby,eng,3.89,2683664,2773745,51992,86236,197621,606158,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...,3.887376,[F. Scott Fitzgerald],1,51992.000000,743273567
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,95,5297,5297,1858012,2303,375751513,9.78037575152e+12,"Oscar Wilde, Jeffrey Eugenides",1891.0,The Picture of Dorian Gray,The Picture of Dorian Gray,eng,4.06,590014,674551,19647,9825,30735,129420,246892,257679,https://images.gr-assets.com/books/1424596966m...,https://images.gr-assets.com/books/1424596966s...,4.055317,"[Oscar Wilde, Jeffrey Eugenides]",2,9823.500000,375751513
95,96,13536860,13536860,18034963,133,345803507,9.7803458035e+12,E.L. James,2012.0,Fifty Shades Freed,"Fifty Shades Freed (Fifty Shades, #3)",eng,3.88,387290,610116,25287,39079,55691,109963,140304,265079,https://images.gr-assets.com/books/1336418837m...,https://images.gr-assets.com/books/1336418837s...,3.879526,[E.L. James],1,25287.000000,345803507
96,97,17245,17245,3165724,2207,393970124,9.78039397013e+12,"Bram Stoker, Nina Auerbach, David J. Skal",1897.0,Dracula,Dracula,eng,3.98,618973,689739,17263,11756,36719,151396,246043,243825,https://images.gr-assets.com/books/1387151694m...,https://images.gr-assets.com/books/1387151694s...,3.976401,"[Bram Stoker, Nina Auerbach, David J. Skal]",3,5754.333333,393970124
97,98,5060378,5060378,6976108,209,307269981,9.78030726998e+12,"Stieg Larsson, Reg Keeland",2006.0,Flickan som lekte med elden,"The Girl Who Played with Fire (Millennium, #2)",eng,4.22,563994,649253,31423,4623,15781,91021,258236,279592,https://images.gr-assets.com/books/1351778881m...,https://images.gr-assets.com/books/1351778881s...,4.220469,"[Stieg Larsson, Reg Keeland]",2,15711.500000,307269981
98,99,11857408,11857408,16813814,147,1612130585,9.78161213058e+12,E.L. James,2011.0,Fifty Shades Darker,"Fifty Shades Darker (Fifty Shades, #2)",eng,3.87,552059,623340,28052,37245,58935,114203,150906,262051,https://images.gr-assets.com/books/1358266080m...,https://images.gr-assets.com/books/1358266080s...,3.868840,[E.L. James],1,28052.000000,1612130585

In [313]:
### Costruisco una lista di ISBN provenienti dal dataset books
list_to_delete = df_books['ISBN'].to_list()

In [314]:
### Ottengo i soli libri che non sono presenti nella lista creata nella riga precedente
df_only_goodbooks = df_goodbooks[~df_goodbooks['ISBN'].isin(list_to_delete)]
df_only_goodbooks.head()

,book_id,goodreads_book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,title,language_code,average_rating,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url,avg_rating,author_list,author_number,shared_number,ISBN
0,1,2767052,2767052,2792775,272,439023483,9.78043902348e+12,Suzanne Collins,2008.0,The Hunger Games,"The Hunger Games (The Hunger Games, #1)",eng,4.34,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,4.341984,[Suzanne Collins],1,155254.000000,439023483
1,2,3,3,4640799,491,439554934,9.78043955493e+12,"J.K. Rowling, Mary GrandPrÃ©",1997.0,Harry Potter and the Philosopher's Stone,Harry Potter and the Sorcerer's Stone (Harry P...,eng,4.44,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...,4.443047,"[J.K. Rowling, Mary GrandPrÃ©]",2,37933.500000,439554934
2,3,41865,41865,3212258,226,316015849,9.78031601584e+12,Stephenie Meyer,2005.0,Twilight,"Twilight (Twilight, #1)",en-US,3.57,3866839,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...,3.571067,[Stephenie Meyer],1,95009.000000,316015849
3,4,2657,2657,3275794,487,61120081,9.78006112008e+12,Harper Lee,1960.0,To Kill a Mockingbird,To Kill a Mockingbird,eng,4.25,3198671,3340896,72586,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...,4.254818,[Harper Lee],1,72586.000000,61120081
4,5,4671,4671,245494,1356,743273567,9.78074327356e+12,F. Scott Fitzgerald,1925.0,The Great Gatsby,The Great Gatsby,eng,3.89,2683664,2773745,51992,86236,197621,606158,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...,3.887376,[F. Scott Fitzgerald],1,51992.000000,743273567
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,95,5297,5297,1858012,2303,375751513,9.78037575152e+12,"Oscar Wilde, Jeffrey Eugenides",1891.0,The Picture of Dorian Gray,The Picture of Dorian Gray,eng,4.06,590014,674551,19647,9825,30735,129420,246892,257679,https://images.gr-assets.com/books/1424596966m...,https://images.gr-assets.com/books/1424596966s...,4.055317,"[Oscar Wilde, Jeffrey Eugenides]",2,9823.500000,375751513
95,96,13536860,13536860,18034963,133,345803507,9.7803458035e+12,E.L. James,2012.0,Fifty Shades Freed,"Fifty Shades Freed (Fifty Shades, #3)",eng,3.88,387290,610116,25287,39079,55691,109963,140304,265079,https://images.gr-assets.com/books/1336418837m...,https://images.gr-assets.com/books/1336418837s...,3.879526,[E.L. James],1,25287.000000,345803507
96,97,17245,17245,3165724,2207,393970124,9.78039397013e+12,"Bram Stoker, Nina Auerbach, David J. Skal",1897.0,Dracula,Dracula,eng,3.98,618973,689739,17263,11756,36719,151396,246043,243825,https://images.gr-assets.com/books/1387151694m...,https://images.gr-assets.com/books/1387151694s...,3.976401,"[Bram Stoker, Nina Auerbach, David J. Skal]",3,5754.333333,393970124
97,98,5060378,5060378,6976108,209,307269981,9.78030726998e+12,"Stieg Larsson, Reg Keeland",2006.0,Flickan som lekte med elden,"The Girl Who Played with Fire (Millennium, #2)",eng,4.22,563994,649253,31423,4623,15781,91021,258236,279592,https://images.gr-assets.com/books/1351778881m...,https://images.gr-assets.com/books/1351778881s...,4.220469,"[Stieg Larsson, Reg Keeland]",2,15711.500000,307269981
98,99,11857408,11857408,16813814,147,1612130585,9.78161213058e+12,E.L. James,2011.0,Fifty Shades Darker,"Fifty Shades Darker (Fifty Shades, #2)",eng,3.87,552059,623340,28052,37245,58935,114203,150906,262051,https://images.gr-assets.com/books/1358266080m...,https://images.gr-assets.com/books/1358266080s...,3.868840,[E.L. James],1,28052.000000,1612130585

### 12. Assuming that each pair (author, title) identifies a book, for each book find the number of times it appears in the books dataset. Which books appear the most times?

In [315]:
df_books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,Book-Rating
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,0.000000
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,4.928571
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,5.000000
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,4.272727
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,0.000000
...,...,...,...,...,...,...,...,...,...
271354,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,7.000000
271355,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,4.000000
271356,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,0.000000
271357,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,0.000000
271358,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,0.000000

In [316]:
### Raggruppo titolo ed autore per ogni libro e conto il numero di elementi per gruppo
group_book= df_books.groupby(['Book-Title', 'Book-Author'], as_index=False)
group_book = group_book.count()
group_book.head()

,Book-Title,Book-Author,ISBN,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,Book-Rating
0,A Light in the Storm: The Civil War Diary of ...,Karen Hesse,1,1,1,1,1,1,1
1,Always Have Popsicles,Rebecca Harvin,1,1,1,1,1,1,1
2,Apple Magic (The Collector's series),Martina Boudreau,1,1,1,1,1,1,1
3,"Ask Lily (Young Women of Faith: Lily Series, ...",Nancy N. Rue,1,1,1,1,1,1,1
4,Beyond IBM: Leadership Marketing and Finance ...,Lou Mobley,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...
251178,Ã?Ã?lpiraten.,Janwillem van de Wetering,1,1,1,1,1,1,1
251179,Ã?Ã?rger mit Produkt X. Roman.,Joan Aiken,1,1,1,1,1,1,1
251180,Ã?Ã?sterlich leben.,Anselm GrÃ?ÃÂ¼n,1,1,1,1,1,1,1
251181,Ã?Ã?stlich der Berge.,David Guterson,1,1,1,1,1,1,1
251182,Ã?Ã?thique en toc,Didier Daeninckx,1,1,1,1,1,1,1

In [317]:
group_book['Count'] = group_book['ISBN']
group_book.drop('Year-Of-Publication', inplace=True , axis=1)
group_book.drop('Image-URL-L', inplace=True , axis=1)
group_book.drop('Image-URL-M', inplace=True , axis=1)
group_book.drop('Image-URL-S', inplace=True , axis=1)
group_book.drop('Book-Rating', inplace=True , axis=1)
group_book.drop('ISBN', inplace=True , axis=1)
group_book.drop('Publisher', inplace=True , axis=1)

In [318]:
### Recupero l'id del value massimo di Count
result = group_book.loc[group_book['Count'].idxmax()]
result

Book-Title          Little Women
Book-Author    Louisa May Alcott
Count                         21
Name: 113850, dtype: object

### 13. Find the author with the highest average rating according to the goodbooks datasets.

In [319]:
### Esplodo la lista di autori cosi' da avere un solo autore per libro
l = df_goodbooks.apply(pd.Series.explode).reset_index()
l

,index,book_id,goodreads_book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,title,language_code,average_rating,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url,avg_rating,author_list,author_number,shared_number,ISBN
0,0,1,2767052,2767052,2792775,272,439023483,9.78043902348e+12,Suzanne Collins,2008.0,The Hunger Games,"The Hunger Games (The Hunger Games, #1)",eng,4.34,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,4.341984,Suzanne Collins,1,155254.000000,439023483
1,1,2,3,3,4640799,491,439554934,9.78043955493e+12,"J.K. Rowling, Mary GrandPrÃ©",1997.0,Harry Potter and the Philosopher's Stone,Harry Potter and the Sorcerer's Stone (Harry P...,eng,4.44,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...,4.443047,J.K. Rowling,2,37933.500000,439554934
2,1,2,3,3,4640799,491,439554934,9.78043955493e+12,"J.K. Rowling, Mary GrandPrÃ©",1997.0,Harry Potter and the Philosopher's Stone,Harry Potter and the Sorcerer's Stone (Harry P...,eng,4.44,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...,4.443047,Mary GrandPrÃ©,2,37933.500000,439554934
3,2,3,41865,41865,3212258,226,316015849,9.78031601584e+12,Stephenie Meyer,2005.0,Twilight,"Twilight (Twilight, #1)",en-US,3.57,3866839,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...,3.571067,Stephenie Meyer,1,95009.000000,316015849
4,3,4,2657,2657,3275794,487,61120081,9.78006112008e+12,Harper Lee,1960.0,To Kill a Mockingbird,To Kill a Mockingbird,eng,4.25,3198671,3340896,72586,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...,4.254818,Harper Lee,1,72586.000000,61120081
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,96,97,17245,17245,3165724,2207,393970124,9.78039397013e+12,"Bram Stoker, Nina Auerbach, David J. Skal",1897.0,Dracula,Dracula,eng,3.98,618973,689739,17263,11756,36719,151396,246043,243825,https://images.gr-assets.com/books/1387151694m...,https://images.gr-assets.com/books/1387151694s...,3.976401,Nina Auerbach,3,5754.333333,393970124
137,96,97,17245,17245,3165724,2207,393970124,9.78039397013e+12,"Bram Stoker, Nina Auerbach, David J. Skal",1897.0,Dracula,Dracula,eng,3.98,618973,689739,17263,11756,36719,151396,246043,243825,https://images.gr-assets.com/books/1387151694m...,https://images.gr-assets.com/books/1387151694s...,3.976401,David J. Skal,3,5754.333333,393970124
138,97,98,5060378,5060378,6976108,209,307269981,9.78030726998e+12,"Stieg Larsson, Reg Keeland",2006.0,Flickan som lekte med elden,"The Girl Who Played with Fire (Millennium, #2)",eng,4.22,563994,649253,31423,4623,15781,91021,258236,279592,https://images.gr-assets.com/books/1351778881m...,https://images.gr-assets.com/books/1351778881s...,4.220469,Stieg Larsson,2,15711.500000,307269981
139,97,98,5060378,5060378,6976108,209,307269981,9.78030726998e+12,"Stieg Larsson, Reg Keeland",2006.0,Flickan som lekte med elden,"The Girl Who Played with Fire (Millennium, #2)",eng,4.22,563994,649253,31423,4623,15781,91021,258236,279592,https://images.gr-assets.com/books/1351778881m...,https://images.gr-assets.com/books/1351778881s...,4.220469,Reg Keeland,2,15711.500000,307269981
140,98,99,11857408,11857408,16813814,147,1612130585,9.78161213058e+12,E.L. James,2011.0,Fifty Shades Darker,"Fifty Shades Darker (Fifty Shades, #2)",eng,3.87,552059,623340,28052,37245,58935,114203,150906,262051,https://images.gr-assets.com/books/1358266080m...,https://images.gr-assets.com/books/1358266080s...,3.868840,E.L. James,1,28052.000000,1612130585

In [320]:
### Calcolo la media per ogni value di avg_rating di ogni autore
group_autori = l.groupby(['author_list'], as_index=False)
group_autori = group_autori['avg_rating'].mean()
group_autori

                  author_list  avg_rating
0              Alan R. Clarke    3.817167
1     B.M. Mooyaart-Doubleday    4.099482
2                Bernard Knox    3.725327
3               CelÃ¢l Ãster    4.138780
4               David J. Skal    3.976401
..                        ...         ...
105             Veronica Roth    4.154579
106           William Golding    3.642994
107           William Goldman    4.253887
108       William Shakespeare    3.734749
109               Yann Martel    3.882868

[110 rows x 2 columns]

In [117]:
### Recupero il value massimo
group_autori[group_autori['avg_rating'] == group_autori['avg_rating'].max()]

    author_list  avg_rating
32   Rufus Beck    4.527866